/* Creating database and table */
create database anudip
use anudip
create table students(SNO int NOT NULL, SNAME varchar(30), COURSE varchar(15), BATCH varchar(10), M1 int, M2 int, M3 int, TOTAL int, AVG float, RESULT varchar(4))
INSERT INTO students VALUES(1, 'SURYA', 'SQL', 'MOR', 65, 66, 70, NULL, NULL, NULL),(2, 'NEHA', 'JAVA', 'EVE', 45, 35, 56, NULL, NULL, NULL),(3, 'JOSHI', 'JAVA', 'MOR', 23, 90, 90, NULL, NULL, NULL),(4, 'VARUN', 'CLANG', 'MOR', 78, 90, 99, NULL, NULL, NULL),(5, 'SASI', 'SQL', 'EVE', 88, 90, 90, NULL, NULL, NULL),(6, 'SHEWATA', 'SQL', 'EVE', 56, 45, 45, NULL, NULL, NULL)
desc students
select * from students

/* 
1)WRITE A QUERY TO UPDATE TOTAL BASED ON M1+M2+M3,AVG BASED ON TOTAL/3,RESULT BASED ON M1&gt;40 AND M2&gt;40 ANDM3&gt;40 TO SET ‘PASS’ OTHERWISE ‘FAIL’ 
*/
update students SET TOTAL = M1+M2+M3 WHERE SNO > 0
update students SET AVG = ((M1+M2+M3)/3) WHERE SNO > 0
UPDATE students SET RESULT = CASE WHEN M1>40 and M2>40 and M3>40 THEN 'PASS' ELSE 'FAIL' END

/* 2)WRITE A QUERY TO UPDATE SNAMES FOR SNO IS 1 AND 5 */
UPDATE students SET SNAME = 'VIKAS' WHERE SNO = 1
UPDATE students SET SNAME = 'ASHUTOSH' WHERE SNO = 5

/* 3)WRITE A QUERY TO SELECT ALL STUDENTS DETAILS RESULT IS ‘PASS’ AND COURSE SHOULD BE EQUAL TO ‘SQL’ */
SELECT * FROM students WHERE RESULT = 'PASS' AND COURSE = 'SQL'

/* 4)WRITE A QUERY TO SELECT WHICH STUDENTS MARKS BELOW 75 AND ABOVE 50 */
SELECT * FROM students WHERE M1<75 AND M2<75 AND M3<75 AND M1>50 AND M2>50 AND M3>50

/* 5)WRITE A QUERY TO SELECT ALL STUDENTS WHICH NAME STARTS WITH ‘S’ LETTER AND ENDS WITH ‘A’ */
SELECT * FROM students WHERE SNAME LIKE "S%A"

/* 6)WRITE A QUERY TO GET ALL STUDENTS DETAILS WHICH STUDENT COURSE IS ‘JAVA’,’CLANG’ */
SELECT * FROM students WHERE COURSE = 'JAVA' OR COURSE = 'CLANG'

/* 7)WRITE A QUERY TO GET ALL COURSE DETAILS WHICH COURSE IS RUNNING IN ‘MOR’ AND ‘EVE’ BATCHES */
SELECT COURSE, BATCH FROM students WHERE BATCH = 'MOR' OR BATCH = 'EVE'

/* 8)WRITE A QUERY TO GET COURSE DETAILS WHICH COURSE IS ONLY ‘MOR’ BUT NOT IN ‘EVE’ BATCH */
SELECT COURSE, BATCH FROM students WHERE BATCH = 'MOR' != 'EVE'